image:
  - Visual Studio 2019

install:
  - set _TROJAN_QT5_BUILD_INFO_="Trojan-Qt5 build from AppVeyor"
  - set QTDIR=C:\Qt\5.14.1\msvc2017\bin
  - set PYDIR=C:\Python36
  - git clone https://github.com/TheWanderingCoel/Trojan-Qt5-Libraries.git C:\TQLibraries
  - curl -LO https://slproweb.com/download/Win32OpenSSL-1_1_1g.exe
  - powershell ".\\Win32OpenSSL-1_1_1g.exe /silent /sp- /suppressmsgboxes /DIR='C:\\TQLibraries\\OpenSSL-Win32'"
  - curl -Lo boost_1_72_0-msvc-14.2-32.exe https://sourceforge.net/projects/boost/files/boost-binaries/1.72.0/boost_1_72_0-msvc-14.2-32.exe/download
  - powershell ".\\boost_1_72_0-msvc-14.2-32.exe /SILENT /SP- /SUPPRESSMSGBOXES /DIR='C:\TQLibraries\boost_1_72_0'"
  - set PATH=%QTDIR%;%PYDIR%;%PATH%;
  - git submodule update --init --recursive
  - cd 3rd\qthttpserver && qmake && nmake && nmake install
  - cd ..\..
  - cd 3rd\yaml-cpp && cmake -G "Visual Studio 16 2019" -A Win32 .
  - msbuild YAML_CPP.sln /p:Configuration=Release /p:Platform="Win32"
  - cd ..\..

init:
  - C:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Community\VC\Auxiliary\Build\vcvarsall.bat x86

build_script:
  - mkdir build && cd build
  - qmake ..
  - nmake
  - cd release
  - windeployqt trojan-qt5.exe
  - del *.o *.h *.cpp *.stash *.qrc *.obj Makefile
  - curl -LO https://github.com/TheWanderingCoel/Trojan-Qt5-DLL/raw/master/libiconv-2.dll
  - curl -LO https://github.com/TheWanderingCoel/Trojan-Qt5-DLL/raw/master/libzbar-0.dll
  - curl -LO https://github.com/TheWanderingCoel/Trojan-Qt5-DLL/raw/master/libssl-1_1.dll
  - curl -LO https://github.com/TheWanderingCoel/Trojan-Qt5-DLL/raw/master/libcrypto-1_1.dll
  - curl -LO https://github.com/TheWanderingCoel/Trojan-Qt5-DLL/raw/master/WinSparkle.dll
  - del /f /s /q vc_redist.x86.exe opengl32sw.dll d3dcompiler_47.dll libGLESV2.dll libEGL.dll Qt5Svg.dll imageformats\qgif.dll iconengines\qsvgicon.dll imageformats\qtga.dll imageformats\qtiff.dll imageformats\qwbmp.dll imageformats\qwebp.dll imageformats\qjpeg.dll imageformats\qsvg.dll iconengines bearer vc_redist.x86.exe
  - rmdir iconengines bearer
  - 7z a Trojan-Qt5-Windows.zip *
  - python ..\..\scripts\checksum.py Trojan-Qt5-Windows.zip Trojan-Qt5-Windows.hash
  - cd ..
  - cd ..

artifacts:
- path: 'build\release\Trojan-Qt5-Windows.*'
  name: Trojan-Qt5

deploy:
  provider: GitHub
  description: "Trojan-Qt5 Release"
  auth_token:
    secure: uAMRAuhJjhHbPRvsKDUGYBDrrDPhlj2q1zHICgjSo7K2CSmVMxHreSMJYqer4y2k
  artifact: Trojan-Qt5
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
