image:
  - Visual Studio 2019

install:
  - set _TROJAN_QT5_BUILD_INFO_="Trojan-Qt5 build from AppVeyor"
  - set QTDIR=C:\Qt\5.14.2\msvc2017\bin
  - set PYDIR=C:\Python36
  - set GODIR=C:\go114-x86
  - set MINGWDIR=C:\MinGW\bin
  - git clone https://github.com/TheWanderingCoel/Trojan-Qt5-Libraries.git C:\TQLibraries
  - curl -LO https://slproweb.com/download/Win32OpenSSL-1_1_1g.exe
  - powershell ".\\Win32OpenSSL-1_1_1g.exe /silent /sp- /suppressmsgboxes /DIR='C:\\TQLibraries\\OpenSSL-Win32'"
  - set PATH=%QTDIR%;%GODIR%;%PYDIR%;%MINGWDIR%;%PATH%;
  - git submodule update --init --recursive
  - cd 3rd\yaml-cpp && cmake -G "Visual Studio 16 2019" -A Win32 .
  - msbuild YAML_CPP.sln /p:Configuration=Release /p:Platform="Win32"
  - cd ..\..
  - cd 3rd\trojan-qt5-libs
  - set CGO_ENABLED=0
  - set GOARCH=386
  - go build -buildmode=c-shared -o trojan-qt5-libs.dll main.go
  - dumpbin /exports trojan-qt5-libs.dll > exports.txt
  - echo LIBRARY TROJAN-QT5-LIBS > trojan-qt5-libs.def
  - echo EXPORTS >> trojan-qt5-libs.def
  - for /f "skip=19 tokens=4" %A in (exports.txt) do echo %A >> trojan-qt5-libs.def
  - lib /def:trojan-qt5-libs.def /out:trojan-qt5-libs.lib /machine:x86
  - dir
  - cd ../..

init:
  - C:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Community\VC\Auxiliary\Build\vcvarsall.bat x86

build_script:
  - mkdir build && cd build
  - qmake ..
  - nmake
  - cd release
  - windeployqt trojan-qt5.exe
  - del *.o *.h *.cpp *.stash *.qrc *.obj Makefile
  - curl -LO https://github.com/TheWanderingCoel/Trojan-Qt5-DLL/raw/master/libiconv-2.dll
  - curl -LO https://github.com/TheWanderingCoel/Trojan-Qt5-DLL/raw/master/libzbar-0.dll
  - curl -LO https://github.com/TheWanderingCoel/Trojan-Qt5-DLL/raw/master/libssl-1_1.dll
  - curl -LO https://github.com/TheWanderingCoel/Trojan-Qt5-DLL/raw/master/libcrypto-1_1.dll
  - curl -LO https://github.com/TheWanderingCoel/Trojan-Qt5-DLL/raw/master/WinSparkle.dll
  - del /f /s /q vc_redist.x86.exe opengl32sw.dll d3dcompiler_47.dll libGLESV2.dll libEGL.dll Qt5Svg.dll imageformats\qgif.dll iconengines\qsvgicon.dll imageformats\qtga.dll imageformats\qtiff.dll imageformats\qwbmp.dll imageformats\qwebp.dll imageformats\qjpeg.dll imageformats\qsvg.dll iconengines bearer vc_redist.x86.exe
  - rmdir iconengines bearer
  - 7z a Trojan-Qt5-Windows.zip *
  - python ..\..\scripts\checksum.py Trojan-Qt5-Windows.zip Trojan-Qt5-Windows.hash
  - cd ..
  - cd ..

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
- path: 'build\release\Trojan-Qt5-Windows.*'
  name: Trojan-Qt5

deploy:
  provider: GitHub
  description: "Trojan-Qt5 Release"
  auth_token:
    secure: uAMRAuhJjhHbPRvsKDUGYBDrrDPhlj2q1zHICgjSo7K2CSmVMxHreSMJYqer4y2k
  artifact: Trojan-Qt5
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
