language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode11
      env: 
        - BADGE=osx
        - _TROJAN_QT5_BUILD_INFO_="Trojan-Qt5 build from Travis-CI"
    - os: linux
      dist: xenial
      sudo: required
      env: 
        - BADGE=linux
        - QT_CI_PACKAGES=qt.qt5.5132.gcc_64,qt.qt5.5132.qtwebengine PATH="$TRAVIS_BUILD_DIR/Qt/5.13.2/gcc_64/bin:${PATH}"
        - _TROJAN_QT5_BUILD_INFO_="Trojan-Qt5 build from Travis-CI"
      addons:
        apt:
          packages:
            - libxkbcommon-x11-0
            - libgl1-mesa-dev
      services:
        - xvfb

before_install:
  - if [ "$BADGE" = "linux" ]; then
      sudo apt-get update;
    fi
  - if [ "$BADGE" = "osx" ]; then
      brew update;
    fi

install:
  - if [ "$BADGE" = "linux" ]; then    
      sudo apt-get install libgl-dev git build-essential g++ python-dev autoconf autotools-dev libicu-dev libbz2-dev checkinstall zlib1g zlib1g-dev python3 -y;
      git clone https://github.com/benlau/qtci.git;
      source qtci/path.env;
      install-qt 5.13.2 >/dev/null 2>&1;
      echo "Installing Zlib 1.2.11...";
      wget https://www.zlib.net/zlib-1.2.11.tar.gz;
      tar -xf zlib-1.2.11.tar.gz;
      cd zlib-1.2.11;
      ./configure --prefix=/usr/local/zlib >/dev/null 2>&1;
      make -j$(nproc) >/dev/null 2>&1;
      sudo make install >/dev/null 2>&1;
      cd ..;
      echo "Installing Pcre 8.43...";
      wget https://ftp.pcre.org/pub/pcre/pcre-8.43.tar.gz;
      tar -xf pcre-8.43.tar.gz;
      cd pcre-8.43;
      ./configure --prefix=/usr/local/pcre >/dev/null 2>&1;
      make -j$(nproc) >/dev/null 2>&1;
      sudo make install >/dev/null 2>&1;
      cd ..;
      echo "Installing ZBar 0.10...";
      wget -O zbar-0.10.tar.gz https://sourceforge.net/projects/zbar/files/zbar/0.10/zbar-0.10.tar.gz/download;
      tar -xf zbar-0.10.tar.gz;
      cd zbar-0.10;
      export CFLAGS="";
      ./configure --prefix=/usr/local/zbar --disable-video --without-qt --without-gtk --without-python >/dev/null 2>&1;
      make -j$(nproc) >/dev/null 2>&1;
      sudo make install >/dev/null 2>&1;
      cd ..;
      echo "Installing libqrencode...";
      git clone https://github.com/fukuchi/libqrencode.git;
      cd libqrencode;
      ./autogen.sh >/dev/null 2>&1;
      ./configure --prefix=/usr/local/qrencode >/dev/null 2>&1;
      make -j$(nproc) >/dev/null 2>&1;
      sudo make install >/dev/null 2>&1;
      cd ..;
      echo "Installing openssl 1.1.1g...";
      wget https://www.openssl.org/source/openssl-1.1.1g.tar.gz;
      tar -xf openssl-1.1.1g.tar.gz;
      cd openssl-1.1.1g;
      ./config --prefix=/usr/local/openssl --openssldir=/usr/local/openssl shared zlib >/dev/null 2>&1;
      make -j$(nproc) >/dev/null 2>&1;
      sudo make install >/dev/null 2>&1;
      cd ..;
      echo "Installing boost 1_72_0...";
      wget -O boost_1_72_0.tar.gz https://sourceforge.net/projects/boost/files/boost/1.72.0/boost_1_72_0.tar.gz/download >/dev/null 2>&1;
      tar -xf boost_1_72_0.tar.gz;
      cd boost_1_72_0/;
      ./bootstrap.sh --prefix=/usr/local/boost >/dev/null 2>&1;
      ./b2 --with-system --with-program_options -j$(nproc);
      sudo ./b2 install >/dev/null 2>&1;
      cd ..;
      echo "Installing libuv";
      wget -O libuv-1.37.0.zip https://github.com/libuv/libuv/archive/v1.37.0.zip;
      unzip libuv-1.37.0.zip;
      cd libuv-1.37.0;
      mkdir build && cd build;
      cmake -D CMAKE_INSTALL_PREFIX=/usr/local/libuv ..;
      make -j$(nproc) >/dev/null 2>&1;
      sudo make install >/dev/null 2>&1;
      cd ..;
      echo "Installing libsodium";
      wget -O https://github.com/jedisct1/libsodium/releases/download/1.0.18-RELEASE/libsodium-1.0.18.tar.gz;
      tar -zxf libsodium-1.0.18.tar.gz;
      cd libsodium-1.0.18;
      ./configure --prefix=/usr/local/libsodium;
      make -j$(nproc) >/dev/null 2>&1;
      sudo make install >/dev/null 2>&1;
      cd ..;
      
    fi
  - if [ "$BADGE" = "osx" ]; then    
      brew install zbar qrencode boost openssl@1.1 zlib pcre python3 libsodium libuv grpc;
      brew reinstall https://raw.githubusercontent.com/Homebrew/homebrew-core/89bf3a54383d884f8b8511c6237325dd5b5ae6ba/Formula/qt.rb --verbose;
      cp -r framework/Sparkle.framework /usr/local/Cellar/qt/5.13.1/lib;
      cp -r framework/LetsMove.framework /usr/local/Cellar/qt/5.13.1/lib;
    fi

before_script:
  - if [ "$BADGE" = "osx" ];   then    export PATH="/usr/local/Cellar/qt/5.13.1/bin:$PATH"; fi

script:
  - git submodule update --init --recursive
  - cd 3rd/qthttpserver
  - qmake && make -j$(nproc) && make install
  - cd ../..
  - cd 3rd/yaml-cpp
  - cmake . && make -j$(nproc)
  - cd ../..
  - if [ "$BADGE" = "osx" ]; then
      mkdir build && cd ./build;
      qmake ../;
      make -j$(nproc);
    fi
  - if [ "$BADGE" = "linux" ]; then
      cd src/privoxy;
      autoheader && autoconf && ./configure;
      cd ../..;
      mkdir build && cd ./build;
      wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage";
      chmod a+x linuxdeployqt-continuous-x86_64.AppImage;
      qmake CONFIG+=release .. PREFIX=/usr;
      make -j$(nproc);
      make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/;
    fi

defore_deploy:
  - if [ "$BADGE" = "osx" ]; then
      xattr -c -r trojan-qt5.app;
      xattr -d com.apple.quarantine trojan-qt5.app;
      macdeployqt trojan-qt5.app -dmg;
      mv trojan-qt5.dmg Trojan-Qt5-macOS.dmg;
      brew link --overwrite python;
      python3 ../scripts/checksum.py Trojan-Qt5-macOS.dmg Trojan-Qt5-macOS.hash;
    fi
  - if [ "$BADGE" = "linux" ]; then
      export LD_LIBRARY_PATH=/usr/loal/zlib/lib:/usr/local/pcre/lib:/usr/local/zbar/lib/:/usr/local/qrencode/lib/:/usr/local/boost/lib/:/usr/local/openssl/lib/:$LD_LIBRARY_PATH;
      ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage;
      mv Trojan-Qt5*.AppImage Trojan-Qt5-Linux.AppImage;
      python3 ../scripts/checksum.py Trojan-Qt5-Linux.AppImage Trojan-Qt5-Linux.hash;
    fi
  - cd ..

deploy:
  provider: release
  file: 
    - build/Trojan-Qt5-macOS.dmg
    - build/Trojan-Qt5-macOS.hash
    - build/Trojan-Qt5-Linux.AppImage
    - build/Trojan-Qt5-Linux.hash
  api_key: $GIT_REPO_TOKEN
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    tags: true
